version: '2.1'
services:
  ganache:
    image: trufflesuite/ganache:v7.4.1
    ports:
      - 127.0.0.1:${GANACHE_RPC_PORT}:8545
    volumes:
      - /Users/stefan/proj/status/test-data/ganache/db/goerli:/test_data/goerli-db
    command: ["-m='${GANACHE_MNEMONIC}'", "-e=10", "--chain.chainId=5", "--database.dbPath=/test_data/goerli-db"]
  uitestganache:
    image: trufflesuite/ganache:v7.4.1
    ports:
      - 127.0.0.1:${GANACHE_RPC_PORT}:8545
    volumes:
      - ${WORKSPACE}/test/ui-test/fixtures/ganache-dbs/goerli:/test_data/goerli-db
    command: ["-m='${GANACHE_MNEMONIC}'", "-e=10", "--chain.chainId=5", "--database.dbPath=/test_data/goerli-db"]
